---
name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: source
      - name: Checkout catlin
        uses: actions/checkout@v2
        with:
          repository: tektoncd/plumbing
          path: catlin
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Install catlin
        run: |
          cd catlin/catlin/cmd/catlin/
          go get github.com/tektoncd/plumbing/catlin/cmd/catlin
      - name: Lint
        run: |
          cd source
          make lint
  test-kind:
    name: Kind
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
          image: "kindest/node:v1.21.1"
          skipClusterCreation: true
      - name: Install dependencies
        run: |
         python3 -m pip install --ignore-installed PyYAML
      - name: Run Test
        run: make test-kind
